// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyC_4MRySHztMVZCik4Oxh9ZD-nWIBgrgqA', // Cập nhật dựa trên cấu hình Firebase
    appId:
        '1:912090799696:web:71b1eeb9720a51af8fbb55', // Cập nhật dựa trên cấu hình Firebase
    messagingSenderId: '912090799696',
    projectId: 'mytracker-bde38',
    authDomain: 'mytracker-bde38.firebaseapp.com',
    storageBucket: 'mytracker-bde38.firebasestorage.app',
    measurementId: 'G-LP28H0EYMN', // Cập nhật dựa trên cấu hình Firebase
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6blsfvr8WlRUc02anR4uM5YKGYv0GRg',
    appId: '1:912090799696:android:631bee804f495a8e8fbb55',
    messagingSenderId: '912090799696',
    projectId: 'mytracker-bde38',
    storageBucket: 'mytracker-bde38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyCcgnbh05AMhdJUSxS9VxUncQBW9bVX9o8', // Cập nhật dựa trên cấu hình Firebase
    appId:
        '1:912090799696:ios:7d550febcab7bb128fbb55', // Cập nhật dựa trên cấu hình Firebase
    messagingSenderId: '912090799696',
    projectId: 'mytracker-bde38',
    storageBucket: 'mytracker-bde38.firebasestorage.app',
    iosClientId:
        '912090799696-6hpt8jhtputjmfq9dqoqccrmqhbsu0iq.apps.googleusercontent.com',
    iosBundleId: 'com.fau.mytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyCcgnbh05AMhdJUSxS9VxUncQBW9bVX9o8', // Cập nhật dựa trên cấu hình Firebase
    appId:
        '1:912090799696:ios:9f03a3fac5fc1b0e8fbb55', // Cập nhật dựa trên cấu hình Firebase
    messagingSenderId: '912090799696',
    projectId: 'mytracker-bde38',
    storageBucket: 'mytracker-bde38.firebasestorage.app',
    iosClientId:
        '912090799696-hgb467v59k4afain8valbv0223cjr1fb.apps.googleusercontent.com', // Cập nhật dựa trên cấu hình Firebase
    iosBundleId: 'com.fau.myTrackerApp', // Cập nhật dựa trên cấu hình Firebase
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'AIzaSyC_4MRySHztMVZCik4Oxh9ZD-nWIBgrgqA', // Cập nhật dựa trên cấu hình Firebase
    appId:
        '1:912090799696:web:4a8ecd3add560c3c8fbb55', // Cập nhật dựa trên cấu hình Firebase
    messagingSenderId: '912090799696',
    projectId: 'mytracker-bde38',
    authDomain: 'mytracker-bde38.firebaseapp.com',
    storageBucket: 'mytracker-bde38.firebasestorage.app',
    measurementId: 'G-1YXFCFNEBE', // Cập nhật dựa trên cấu hình Firebase
  );
}
