// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdiuMHZFG4svnOZYMShHZBY4YdX8d7oQs',
    appId: '1:655120265431:web:615a3bba0c11f8f1b40092',
    messagingSenderId: '655120265431',
    projectId: 'package-tracker-84222',
    authDomain: 'package-tracker-84222.firebaseapp.com',
    storageBucket: 'package-tracker-84222.firebasestorage.app',
    measurementId: 'G-F7CBLDQ0GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqo4pis087pDaxhTuXTnWRc9aysRxTs-U',
    appId: '1:655120265431:android:321518e17674a1a7b40092',
    messagingSenderId: '655120265431',
    projectId: 'package-tracker-84222',
    storageBucket: 'package-tracker-84222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf7GHGwbBPYNImrBgWDIB-iMU7N7OWEIQ',
    appId: '1:655120265431:ios:3bcc25008dcf5c52b40092',
    messagingSenderId: '655120265431',
    projectId: 'package-tracker-84222',
    storageBucket: 'package-tracker-84222.firebasestorage.app',
    iosClientId: '655120265431-th7usoq1s7j177g5rpqjb859snt2vc52.apps.googleusercontent.com',
    iosBundleId: 'com.fau.mytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf7GHGwbBPYNImrBgWDIB-iMU7N7OWEIQ',
    appId: '1:655120265431:ios:f949d651952d2a91b40092',
    messagingSenderId: '655120265431',
    projectId: 'package-tracker-84222',
    storageBucket: 'package-tracker-84222.firebasestorage.app',
    iosClientId: '655120265431-l6qfjbgg6mal1pq3dothrmt7m7tb4j5o.apps.googleusercontent.com',
    iosBundleId: 'com.fau.myTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdiuMHZFG4svnOZYMShHZBY4YdX8d7oQs',
    appId: '1:655120265431:web:dabaccd090505998b40092',
    messagingSenderId: '655120265431',
    projectId: 'package-tracker-84222',
    authDomain: 'package-tracker-84222.firebaseapp.com',
    storageBucket: 'package-tracker-84222.firebasestorage.app',
    measurementId: 'G-9K16CT8XM6',
  );

}